version: "3.10"
services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongo_db/lamoda_parser
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db
      - redis_cache

  mongo_db:
    image: mongo:4.4
    container_name: "mongo_db"
    ports:
      - "27017:27017"
    networks:
      - custom

  redis_cache:
    image: redis:latest
    container_name: "redis_cache"
    ports:
      - "6379:6379"
    networks:
      - custom

  kafka:
      image: confluentinc/cp-kafka:5.3.1
      container_name: "kafka"
      ports:
          - "9092:9092"
      environment:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_CREATE_TOPICS: "lamoda_parser:1:1,other_topic:1:1,__consumer_offsets:50:1"
      depends_on:
          - zookeeper
      networks:
          - custom



  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    container_name: zookeeper
    ports:
    - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - custom


networks:
  custom:
    driver: bridge

